INTERACTIVE_MODELS_PATH: "./RiTM/weights"
EXPS_PATH: "./RiTM/experiments"

# Evaluation datasets
GRABCUT_PATH: "./RiTM/datasets/GrabCut"
BERKELEY_PATH: "./RiTM/datasets/Berkeley"
DAVIS_PATH: "./RiTM/datasets/DAVIS"
COCO_MVAL_PATH: "./RiTM/datasets/COCO_MVal"

# Train datasets
SBD_PATH: "./RiTM/datasets/SBD/dataset"
COCO_PATH: "./RiTM/datasets/coco2017"
LVIS_PATH: "./RiTM/datasets/LVIS"
OPENIMAGES_PATH: "./RiTM/datasets/OpenImages"
PASCALVOC_PATH: "./RiTM/datasets/PascalVOC"
ADE20K_PATH: "./RiTM/datasets/ADE20K"
LVIS_v1_PATH: "./RiTM/datasets/LVIS_v1"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./RiTM/pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./RiTM/pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./RiTM/pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./RiTM/pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
